CREATE TABLE "MISSION" (
    "id" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "place" VARCHAR(255) NOT NULL,
    "completed" BOOLEAN
     );

CREATE TABLE "AGENT" (
     "id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
     "name" VARCHAR(255),
     "born" DATE
     );


CREATE TABLE "ASSIGNMENT" (
  "id" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "from" DATE,
   "to" DATE,
   "agentId" BIGINT REFERENCES AGENT (id) on delete cascade,
   "missionId" BIGINT REFERENCES MISSION (id) on delete cascade
   );